// my_class.h
#ifndef CONST_H
#define CONST_H

#define G_LED_COUNT 8

#define DEBOUNCE_DELAY 50

#define LONG_BUTTON_PRESS_MS 4000

#define BRIGHTNESS 250

#define ANIMATION_HIT 1
#define ANIMATION_SEEK 2
#define ANIMATION_BLANK 3
#define ANIMATION_COUNT 4
#define ANIMATION_HUNT 5
#define ANIMATION_PRESCORE 6

#define GAME_MODE_SHOOTING_GALLERY 0
#define GAME_MODE_ALL_TARGETS_ON 1
#define GAME_MODE_COLOR_HUNT 2
#define MAX_MODES 3
// dont count these as a game modes
#define GAME_MODE_SETUP 4
#define GAME_MODE_SCORE 5

//#define SHOOTING_GALLERY_ROUND_TIME (60*1000)
#define END_GAME_PRE_SCORE_SHOW_TIME (2*1000)
#define END_GAME_SCORE_SHOW_TIME (5*1000)

#define GREEN_COLOR 0
#define BLUE_COLOR 1
#define PURPLE_COLOR 2
#define ORANGE_COLOR 3
#define YELLOW_COLOR 4
#define RED_COLOR 5

#endif // CONST_H


