// my_class.h
#ifndef CONST_H
#define CONST_H

#define G_LED_COUNT 8

#define DEBOUNCE_DELAY 50

#define LONG_BUTTON_PRESS_MS 4000

#define BRIGHTNESS 250

#define ANIMATION_HIT 1
#define ANIMATION_SEEK 2
#define ANIMATION_BLANK 3

#define GAME_MODE_SHOOTING_GALLERY 1
#define GAME_MODE_ALL_TARGETS_ON 2

#endif // CONST_H


